import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local"; // استيراد localFont
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ramsina = localFont({
  src: [
    {
      path: "../public/Ramsina-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-ramsina",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ramsina.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
